; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

; PlatformIO Project Configuration File

[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

; Tốc độ Serial Monitor (để đồng bộ với code Serial.begin)
monitor_speed = 115200

; --- CẤU HÌNH ÉP XUNG & BỘ NHỚ CHO BẢN N16R8 ---
; Cấu hình bộ nhớ Flash 16MB
board_upload.flash_size = 16MB
board_build.partitions = default_16MB.csv

; Bật giao tiếp OPI cho PSRAM và Flash (Bắt buộc với N16R8)
board_build.arduino.memory_type = qio_opi

; Kích hoạt cờ sử dụng PSRAM
build_flags = 
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue

; --- QUẢN LÝ THƯ VIỆN TỰ ĐỘNG ---
; PlatformIO sẽ tự tải các thư viện này về dự án
lib_deps =
    sandeepmistry/LoRa @ ^0.8.0
    blynkkk/Blynk @ ^1.3.2
    bblanchon/ArduinoJson @ ^7.0.4
